title: Colin Scotland # your name (or website title) here
logo: "/images/cs.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm an enthusiastic advocate of Data Analysis with an academic background in 
  Physics and over 25 years' experience in Microelectronics Engineering and 
  Manufacturing Management.
  <a href="https://www.linkedin.com/in/colin-scotland-b83114238/">View My LinkedIn Profile</a> 
  
  
  
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
